config/routes.rb
Rails.application.routes.draw do
  get 'search/search'
  devise_for :admin, controllers: {
    sessions:      'admin/sessions',
    passwords:     'admin/passwords',
    registrations: 'admin/registrations'
  }
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    namespace :admin do
      resources :items
      resources :genres, except:[:new,:show]
      resources :customers, except:[:new,:create]
      resources :orders, only:[:show,:update] 
      resources :order_details, only:[:update]
      get '' => 'homes#top'
    end
    
    scope module: :public do
      resource :customers,only:[:show,:edit,:update]
      devise_for :customers, path_names: { edit: 'fare'}
      resources :items,only:[:index,:show]
      post 'orders/comfirm' => 'orders#comfirm'
      get 'orders/thanks' => 'orders#thanks'
      delete 'cart_items/destroy_all' => 'cart_items#destroy_all'
      resources :cart_items, only:[:index,:update,:create,:destroy]
      resources :orders, only:[:index,:show,:new,:create] 
      resources :addresses, except:[:new]
      get 'top' => 'homes#top'
      root to: 'homes#top'
      get 'about' => 'homes#about'
      get 'customers/quit' => 'customers#quit'
      patch 'customers/leave' => 'customers#leave'
    end
end

app/models/address.rb
class Address < ApplicationRecord
	belongs_to :customer
	
  def full_address
    '〒' + postal_code + ' ' + address + ' ' + name
  end
  
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
	belongs_to :customer
	belongs_to :item
	
  def subtotal
   item.with_tax_price*amount
  end
  
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  def find_for_authentication(conditions)
   super(conditions.merge(is_deleted: true))
  end
  
  has_many :orders, dependent: :destroy
  has_many :addresses, dependent: :destroy
  has_many :cart_items, dependent: :destroy
end

app/models/genre.rb
class Genre < ApplicationRecord
	has_many :items, dependent: :destroy
end

app/models/item.rb
class Item < ApplicationRecord
	belongs_to :genre
	has_many :cart_items, dependent: :destroy
	has_many :order_details, dependent: :destroy
	attachment :image
	
	def with_tax_price
    (price * 1.1).floor
  end
  
end

app/models/order.rb
class Order < ApplicationRecord
	belongs_to :customer
	has_many :order_details, dependent: :destroy
	enum payment_method: {credit_card: 0, transfer: 1 }
	enum status: { waited: 0, comfirm: 1, making: 2, posting: 3, posted: 4 }
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
	belongs_to :item
	belongs_to :order
  enum making_status: {impossible: 0, waited: 1, making: 2, maked: 3 }
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
	before_action :authenticate_admin!
	
	def index
	 @genre = Genre.new
	 @genres = Genre.all
	end

	def create
	 genre=Genre.new(genre_params)
	 genre.save
	 redirect_to admin_genres_path
	end

	def edit
	 @genre = Genre.find(params[:id])
	end

	def update
	 genre = Genre.find(params[:id])
	 genre.update(genre_params)
	 redirect_to admin_genres_path
	end
	
	private
	def genre_params
		params.require(:genre).permit(:name)
	end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
	before_action :authenticate_admin!
	
 def top
  if params[:search].present?
   @customer=Customer.find(params[:search][:value].to_i)
   @orders =@customer.orders.page(params[:page]).reverse_order
  else
   @orders=Order.page(params[:page]).reverse_order
   @total_amount = 0
  end
 end

end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
	before_action :authenticate_admin!
	
	def new
	 @item=Item.new
	end
	
	def create
	 item=Item.new(item_params)
	 item.save
	 redirect_to admin_item_path(item)
	end
	
	def index
	 @items = Item.page(params[:page]).reverse_order
	end
	
	def show
	 @item=Item.find(params[:id])
	end
	
	def edit
	 @item=Item.find(params[:id])
	end
	
	def update
	 item=Item.find(params[:id])
	 item.update(item_params)
	 redirect_to admin_items_path
	end
	
	private
		def item_params
		 params.require(:item).permit(:genre_id,:name, :image ,:introduction, :price, :is_active)
		end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
 before_action :authenticate_admin!

 def show
  @find_order = Order.find(params[:id])
  @customer_name = @find_order.customer.last_name + @find_order.customer.first_name
 end
 
 def update
   order = Order.find(params[:id])
   order.update(order_params)
   order_details = order.order_details
   if order.status_before_type_cast == 1 && order_details.where(making_status: 0).count == order.order_details.count
      order_details.each do |order_detail|
      order_detail.making_status = 1
      order_detail.update(order_detail_params)
      end
     redirect_to admin_path 
   else
    redirect_to admin_path
   end
 end
 
 private
  def order_params
   params.require(:order).permit(:customer_id,:postal_code, :address, :name, :shipping_cost, :total_payment, :payment_method, :status)
  end
  
  def order_detail_params
   params.require(:order).permit(:making_status)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

protected

  def configure_permitted_parameters
   devise_parameter_sanitizer.permit(:sign_up, keys:[:last_name,:first_name,:last_name_kana,:first_name_kana,:postal_code,:address,:telephone_number])
  end
 	
  def after_sign_in_path_for(resorce)
    case resorce
    when Admin
      admin_path
    when Customer
      root_path
    end
  end
 	
  def after_sign_out_path_for(resorce)
   case resorce
    when :admin
       new_admin_session_path
    when :customer
      root_path
   end
  end
  
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  
def search
  @value = params[:name]        #データを代入
  @datas = search_for(@value) #def search_forを実行(引数に検索ワードと検索方法)
end

private
  def search_for(value)
    Item.where(name: value).or(Item.where("name LIKE ?", "%#{value}%"))
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/admin/genres/edit.html.erb
<div class="container">
 <div class="row">
  <h2 class="col-sm-6 col-md-4 col-lg-3 mr-2 mt-3 text-center bg-light">ジャンル編集</h2>
 </div>
 <div class="row">
  <div class="col-sm-10 col-md-8 col-lg-6 mr-5 mt-3">
   <%= form_with model:@genre, url: admin_genre_path, local:true do |f| %>
    <div class="form-group row form-inline mt-3">
   	 <%= f.label:ジャンル名,class:"mr-4"%> 
   	 <%= f.text_field :name,class:"mr-4 form-control name" %> 
   	 <%= f.submit "変更を保存",class:"mr-4 btn btn-success" %>
    </div>
   <% end %>
  </div>
 </div>

app/views/admin/genres/index.html.erb
<div class="container">
 <div class="row">
  <h2 class="col-sm-6 col-md-4 col-lg-4 mr-2 mt-3 text-center bg-light">ジャンル一覧・追加</h2>
 </div>
 <div class="mt-3 row">
  <div class="col-sm-10 col-md-8 col-lg-6 mr-2 mt-3">
   <%= form_with model:@genre,url: admin_genres_path, local:true do |f| %>
  	<%= f.label:ジャンル名,class:"mr-4" %>
  	<%= f.text_field :name,class:"mr-4",placeholder:'ジャンル名' %>
  	<%= f.submit "新規登録",class:"mr-4 btn btn-success" %>
   <% end %>
  </div>
 </div>
 <div class="mt-5 row">
  <div class="col-sm-8 col-md-6 col-lg-4 mr-2 mt-3">
  	<table class="table table-hover">
  		<thead>
  			<tr>
  				<th colspan="2">ジャンル</th>
  			</tr>
  		</thead>
  		<tbody>
  			<% @genres.each do |genre| %>
  			<tr>
  				<th><%= genre.name %></th>
  				<th><%= link_to"編集する",edit_admin_genre_path(genre),class:"btn btn-success" %></th>
  			</tr>
  			<% end %>
  		</tbody>
  	</table>
 </div>
</div>

app/views/admin/items/edit.html.erb
<div class="container">
 <div class="row">
  <h2 class="col-sm6 col-md-4 col-lg-3 mr-2 mt-3 text-center bg-light">商品編集</h2>
 </div>
 <div class="mt-5 row">
 	<div class="col-sm-12 col-md-10 col-lg-8 m-auto">
 	 <%= form_with model:@item,url: admin_item_path,local:true do |f| %>
 	<div class="form-group row">
 	 <%= f.label :商品画像,class:"mt-2 col-sm-4 col-md-3 col-lg-3 col-form-label text-right" %>
 	 <%= f.attachment_field :image,class:"mt-2 col-sm-8 col-md-7 col-lg-5" %>
 	</div>
 	<div class="form-group row">
 	 <%= f.label :商品名,class:"mt-2 col-sm-4 col-md-3 col-lg-3 col-form-label text-right" %>
 	 <%= f.text_field :name,class:"mt-2 col-sm-8 col-md-8 col-lg-5" %>
 	</div>
 	<div class="form-group row">
 	 <%= f.label :商品紹介,class:"mt-2 col-sm-4 col-md-3 col-lg-3 col-form-label text-right" %>
 	 <%= f.text_area :introduction,class:"mt-2 col-sm-8 col-md-7 col-lg-5" %>
 	</div>
 	<div class="form-group row">
 	 <%= f.label :ジャンル,class:"mt-2 col-sm-4 col-md-3 col-lg-3 col-form-label text-right" %>
 	 <%= f.select :genre_id, options_from_collection_for_select(Genre.all,:id,:name),class:"col-sm-8 col-md-3 col-lg-5" %>
 	</div>
 	<div class="form-group row">
 	 <%= f.label :税抜価格,class:"mt-2 col-sm-4 col-md-3 col-lg-3 col-form-label text-right" %>
 	 <%= f.text_field :price,class:"mt-1 col-sm-8 col-md-7 col-lg-5" %><p class="ml-1 mt-1">円</p>
 	</div>
 	 <div class="form-group row">
 	 	<%= f.label :販売ステータス,class:"mt-2 col-sm-4 col-md-3 col-lg-3 col-form-label text-right" %>
 	 	<div class="mt-2 col-sm-8 col-md-7 col-lg-5">
	 	  <%= f.radio_button :is_active, true %>
	     <%= f.label :is_active, "販売中" %>
	    <%= f.radio_button :is_active, false %>
	     <%= f.label :is_active, "販売停止中" %>
	  </div>
	  </div>
 	 	<div class="mt-1 col-sm-5 col-md-4 col-lg-3 m-auto">
	 	  <%= f.submit "変更を保存", class:"btn btn-success w-100" %>
	  </div>
  <% end %> 
  </div>
 </div>
</div>

app/views/admin/items/index.html.erb
<div class="container">
 <div class="row">
 <h2 class="col-sm6 col-md-4 col-lg-3 mr-2 mt-3 text-center bg-light">商品一覧</h2>
  <%= link_to"", new_admin_item_path,class: 'mt-3 fas fa-plus-circle fa-3x size ml-auto' %>
 </div>
 <div class="row mt-5">
 <table class="col-sm-12 col-md-10 col-lg-8 m-auto table table-hover">
   <thead>
    <tr>
      <th>商品ID</th>
      <th>商品名</th>
      <th>税抜価格</th>
      <th>ジャンル</th> 
       <th>販売ステータス</th> 
  </tr>
   </thead>
   <tbody>
    <% @items.each do |item| %>
    <tr>
      <th><%= item.id %></th>
      <th><%= link_to item.name,admin_item_path(item) %></th>
      <th><%= number_to_currency(item.price,:precision => 0,:format => "%n") %></th>
      <th><%= item.genre.name %></th> 
      <th>
	       <% if item.is_active == true then %>
	        <p class="text-success"><strong>販売中</strong></p>
	   　  <% else %>
	   　   <p class="text-secondary"><strong>販売停止</strong></p>
        <% end %>
	     </th> 
  </tr>
  <% end %>
   </tbody>
 </table>
 </div>
 <div class="row">
  <div class="col-sm-12 col-md-12 col-lg-3 m-auto">
   <%= paginate @items ,class:"m-auto"%>
  </div>
 </div>
 </div>

app/views/admin/items/new.html.erb
<div class="container">
 <div class="row">
  <h2 class="col-sm6 col-md-4 col-lg-3 mr-2 mt-3 text-center bg-light">商品新規登録</h2>
 </div>
 <div class="mt-5 row">
 	<div class="col-sm-12 col-md-10 col-lg-8 m-auto">
 	 <%= form_with model:@item, url: admin_items_path, local:true do |f| %>
 	<div class="form-group row">
 	 <%= f.label :商品画像,class:"mt-2 col-sm-4 col-md-3 col-lg-3 col-form-label text-right" %>
 	 <%= f.attachment_field :image,class:"mt-2 col-sm-8 col-md-7 col-lg-5" %>
 	</div>
 	<div class="form-group row">
 	 <%= f.label :商品名,class:"mt-2 col-sm-4 col-md-3 col-lg-3 col-form-label text-right" %>
 	 <%= f.text_field :name,class:"mt-2 col-sm-8 col-md-8 col-lg-5",placeholder:'商品名' %>
 	</div>
 	<div class="form-group row">
 	 <%= f.label :商品紹介,class:"mt-2 col-sm-4 col-md-3 col-lg-3 col-form-label text-right" %>
 	 <%= f.text_area :introduction,class:"mt-2 col-sm-8 col-md-7 col-lg-5",placeholder:'ここに説明文を記載します。' %>
 	</div>
 	<div class="form-group row">
 	 <%= f.label :ジャンル,class:"mt-2 col-sm-4 col-md-3 col-lg-3 col-form-label text-right" %>
 	 <%= f.select :genre_id, options_from_collection_for_select(Genre.all,:id,:name),class:"col-sm-8 col-md-3 col-lg-5" %>
 	</div>
 	<div class="form-group row">
 	 <%= f.label :税抜価格,class:"mt-2 col-sm-4 col-md-3 col-lg-3 col-form-label text-right" %>
 	 <%= f.text_field :price,class:"mt-1 col-sm-8 col-md-7 col-lg-5",placeholder:'1000'%><p class="ml-1 mt-1">円</p>
 	</div>
 	 <div class="form-group row">
 	 	<%= f.label :販売ステータス,class:"mt-2 col-sm-4 col-md-3 col-lg-3 col-form-label text-right" %>
 	 	<div class="mt-2 col-sm-8 col-md-7 col-lg-5">
	 	  <%= f.radio_button :is_active, true %>
	     <%= f.label :is_active, "販売中" %>
	    <%= f.radio_button :is_active, false %>
	     <%= f.label :is_active, "販売停止中" %>
	  </div>
	  </div>
 	 	<div class="mt-1 col-sm-5 col-md-4 col-lg-3 m-auto">
	 	  <%= f.submit "新規登録", class:"btn btn-success w-100" %>
	  </div>
  <% end %> 
  </div>
 </div>
</div>

app/views/admin/items/show.html.erb
<div class="container">
 <div class="row">
  <h2 class="col-sm-6 col-md-4 col-lg-3 mr-2 mt-3 text-center bg-light">商品詳細</h2>
 </div>
 <div class="row">
  <div class="col-sm-6 col-md-4 col-lg-4 mr-2 mt-4">
   <%= attachment_image_tag	@item, :image, :fill,100,100, size:"300x200", format: 'jpeg' %>
  </div>
  <table class="table table-borderless col-sm-12 col-md-6 col-lg-6 mr-2 mt-3 d-flex align-items-center">
   <thead>
	  <tr><th>商品名</th><td><%= @item.name %></td></tr>
	  <tr><th>商品詳細</th><td><%= @item.introduction %></td></tr>
	  <tr><th>ジャンル</th><td><%= @item.genre.name %></td></tr>
	  <tr><th>税込価格<br>（税抜価格）</th>
	    <td><p><%= number_to_currency(@item.price*1.1,:precision => 0, :format => "%n%u", :unit => "円") %>
	     <br>（<%= number_to_currency(@item.price,:precision => 0, :format => "%n%u", :unit => "円") %> ）</p>
	    </td>
	  </tr> 
	  <tr><th>販売ステータス</th>
	      <td>
	       <% if @item.is_active == true then %>
	        <p class="text-success"><strong>販売中</strong></p>
	     <% else %>
	      <p class="text-secondary"><strong>販売停止</strong></p>
	    <% end %>
	   </td>
	  </tr>
  </table>
  </div>
  <div class="row">
  <%= link_to"編集する", edit_admin_item_path,class: "btn btn-success m-auto" %>
 </div>
</div>

app/views/admin/orders/show.html.erb
<div class="container">
 <div class="row">
 <h2 class="col-sm6 col-md-4 col-lg-3 mr-2 mt-3 text-center bg-light">注文履歴詳細</h2>
 </div>
 <div class="row mt-5">
 <table class="col-sm-12 col-md-10 col-lg-8 m-auto table table-borderless">
    <tr>
      <th>購入者</th>
      <td><%= link_to @customer_name,admin_customer_path(@find_order.customer_id) %></td>
    </tr>
    <tr>
      <th>注文日</th>
      <td><%= @find_order.created_at.strftime('%Y/%m/%d') %></td>
    </tr>
    <tr>
      <th>配送先</th>
      <td>
        〒
        <%= @find_order.postal_code %>
        <%= @find_order.address %><br>
        <%= @find_order.name %>
      </td>
    </tr>
    <tr>
      <th>支払方法</th> 
      <td><%= @find_order.payment_method_i18n %></td>
    </tr>
     <tr>
      <th>注文ステータス</th> 
      <td>
        <%= form_with model:@find_order, url: admin_order_path(@find_order), local:true do |f| %>
        <%= f.select :status, Order.statuses_i18n.invert %>
        <%= f.submit "更新" ,class:"btn btn-success" %>
        <% end %>
        </td>
    </tr>
  </table>
 </div>
 <div class="row mt-5">
 <table class="col-sm-12 col-md-10 col-lg-8 m-auto table table-hover">
   <thead>
    <tr>
      <th>商品名</th>
      <th>単価（税込）</th>
      <th>数量</th>
      <th>小計</th>
      <th>製作ステータス</th>
    </tr>
   </thead>
  <tbody>
    <% @find_order.order_details.each do |order_detail| %>
    <tr>
      <th><%= order_detail.item.name %></th>
      <th><%= order_detail.price %></th>
      <th><%= order_detail.amount %></th>
      <th><%= number_to_currency(order_detail.price*order_detail.amount,:precision => 0,:format => "%n") %></th>
      <th>
        <%= form_with model:order_detail, url: admin_order_detail_path(order_detail), local:true do |f| %>
        <%= f.select :making_status, OrderDetail.making_statuses_i18n.invert %>
        <%= f.hidden_field :order_id, value: order_detail.order_id %>
        <%= f.submit "更新" ,class:"btn btn-success" %>
        <% end %>
	    </th> 
    </tr>
  <% end %>
  </tbody>
 </table>
 <table class="col-sm-12 col-md-10 col-lg-4 m-auto table table-borderless">
    <tr>
      <th><strong>商品合計</strong></th>
      <td><%= number_to_currency(@find_order.total_payment,:precision => 0, :format => "%n%u", :unit => "円") %></td>
    </tr>
    <tr>
      <th><strong>送料合計</strong></th>
      <td><%= number_to_currency(@find_order.shipping_cost,:precision => 0, :format => "%n%u", :unit => "円") %></td>
    </tr>
    <tr>
      <th><strong>請求金額合計</strong></th>
      <td><%= number_to_currency(@find_order.total_payment+@find_order.shipping_cost,:precision => 0, :format => "%n%u", :unit => "円") %></td>
    </tr>
 </table>
 </div>
</div>