config/routes.rb
Rails.application.routes.draw do
  get 'search/search'
  devise_for :admin, controllers: {
    sessions:      'admin/sessions',
    passwords:     'admin/passwords',
    registrations: 'admin/registrations'
  }
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    namespace :admin do
      resources :items
      resources :genres, except:[:new,:show]
      resources :customers, except:[:new,:create]
      resources :orders, only:[:show,:update] 
      resources :order_details, only:[:update]
      get '' => 'homes#top'
    end
    
    scope module: :public do
      resource :customers,only:[:show,:edit,:update]
      devise_for :customers, path_names: { edit: 'fare'}
      resources :items,only:[:index,:show]
      post 'orders/comfirm' => 'orders#comfirm'
      get 'orders/thanks' => 'orders#thanks'
      delete 'cart_items/destroy_all' => 'cart_items#destroy_all'
      resources :cart_items, only:[:index,:update,:create,:destroy]
      resources :orders, only:[:index,:show,:new,:create] 
      resources :addresses, except:[:new]
      get 'top' => 'homes#top'
      root to: 'homes#top'
      get 'about' => 'homes#about'
      get 'customers/quit' => 'customers#quit'
      patch 'customers/leave' => 'customers#leave'
    end
end

app/models/address.rb
class Address < ApplicationRecord
	belongs_to :customer
	
  def full_address
    '〒' + postal_code + ' ' + address + ' ' + name
  end
  
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
	belongs_to :customer
	belongs_to :item
	
  def subtotal
   item.with_tax_price*amount
  end
  
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  def find_for_authentication(conditions)
   super(conditions.merge(is_deleted: true))
  end
  
  has_many :orders, dependent: :destroy
  has_many :addresses, dependent: :destroy
  has_many :cart_items, dependent: :destroy
end

app/models/genre.rb
class Genre < ApplicationRecord
	has_many :items, dependent: :destroy
end

app/models/item.rb
class Item < ApplicationRecord
	belongs_to :genre
	has_many :cart_items, dependent: :destroy
	has_many :order_details, dependent: :destroy
	attachment :image
	
	def with_tax_price
    (price * 1.1).floor
  end
  
end

app/models/order.rb
class Order < ApplicationRecord
	belongs_to :customer
	has_many :order_details, dependent: :destroy
	enum payment_method: {credit_card: 0, transfer: 1 }
	enum status: { waited: 0, comfirm: 1, making: 2, posting: 3, posted: 4 }
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
	belongs_to :item
	belongs_to :order
  enum making_status: {impossible: 0, waited: 1, making: 2, maked: 3 }
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
	before_action :authenticate_admin!
	
 def top
  if params[:search].present?
   @customer=Customer.find(params[:search][:value].to_i)
   @orders =@customer.orders.page(params[:page]).reverse_order
  else
   @orders=Order.page(params[:page]).reverse_order
   @total_amount = 0
  end
 end

end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
	before_action :authenticate_admin!
	
	def new
	 @item=Item.new
	end
	
	def create
	 item=Item.new(item_params)
	 item.save
	 redirect_to admin_item_path(item)
	end
	
	def index
	 @items = Item.page(params[:page]).reverse_order
	end
	
	def show
	 @item=Item.find(params[:id])
	end
	
	def edit
	 @item=Item.find(params[:id])
	end
	
	def update
	 item=Item.find(params[:id])
	 item.update(item_params)
	 redirect_to admin_items_path
	end
	
	private
		def item_params
		 params.require(:item).permit(:genre_id,:name, :image ,:introduction, :price, :is_active)
		end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

protected

  def configure_permitted_parameters
   devise_parameter_sanitizer.permit(:sign_up, keys:[:last_name,:first_name,:last_name_kana,:first_name_kana,:postal_code,:address,:telephone_number])
  end
 	
  def after_sign_in_path_for(resorce)
    case resorce
    when Admin
      admin_path
    when Customer
      root_path
    end
  end
 	
  def after_sign_out_path_for(resorce)
   case resorce
    when :admin
       new_admin_session_path
    when :customer
      root_path
   end
  end
  
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  
def search
  @value = params[:name]        #データを代入
  @datas = search_for(@value) #def search_forを実行(引数に検索ワードと検索方法)
end

private
  def search_for(value)
    Item.where(name: value).or(Item.where("name LIKE ?", "%#{value}%"))
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
<body>
 <header>
  <nav class="navbar navbar-expand-lg navbar-dark bg-warning">
   <div class="container">
    <a class="navbar-brand">Nagano_Cake</a>
    <% if customer_signed_in? %>
     <p class="mt-3 ml-5", style="padding-left:100px; color:red;">ようこそ<%= current_customer.last_name %>さん！</p>
    <% end %>
     <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggel navigation">
      <span class="navbar-toggler-icon"></span>
     </button>
      <div class="collapse navbar-collapse" id="navbarNavDropDown">
    <div class="row  ml-auto">
     <div class="d-flex flex-column">
      <ul class="navbar-nav">
       <% if admin_signed_in? %>
        <%= link_to"商品一覧",admin_items_path,class: 'btn btn-outline-secondary', style: "margin-right: 20px;" %>
        <%= link_to"会員一覧",admin_customers_path,class: 'btn btn-outline-secondary', style: "margin-right: 20px;" %>
        <%= link_to"注文履歴一覧",admin_path,class: 'btn btn-outline-secondary', style: "margin-right: 20px;" %>
        <%= link_to"ジャンル一覧",admin_genres_path,class: 'btn btn-outline-secondary', style: "margin-right: 20px;" %>
        <%= link_to"ログアウト",destroy_admin_session_path,method: :delete,class: 'btn btn-outline-secondary' %>
       <% elsif customer_signed_in? %>
        <%= link_to"マイページ",customers_path,class: 'btn btn-outline-secondary', style: "margin-right: 20px;" %>
        <%= link_to"商品一覧",items_path,class: 'btn btn-outline-secondary', style: "margin-right: 20px;" %>
        <%= link_to"カート",cart_items_path,class: 'btn btn-outline-secondary', style: "margin-right: 20px;" %>
        <%= link_to"ログアウト",destroy_customer_session_path,method: :delete, class: 'btn btn-outline-secondary' %>
       <% else %>
        <%= link_to"About",about_path,class: 'btn btn-outline-secondary', style: "margin-right: 20px;" %>
        <%= link_to"商品一覧",items_path,class: 'btn btn-outline-secondary', style: "margin-right: 20px;" %>
        <%= link_to"新規登録",new_customer_registration_path,class: 'btn btn-outline-secondary', style: "margin-right: 20px;" %>
        <%= link_to"ログイン",new_customer_session_path,class: 'btn btn-outline-secondary' %>
       <% end %>
     </ul>
     <div class="mt-2 search-form">
      <%= form_with model:@find_item, url: search_search_path, method: :get, local: true do |f| %>
      <%= f.text_field :name, size: "26x4", style: "margin-left: 115px;" %>
      <span class="search-button col-xs-12 text-right">
        <%= f.submit :"検索" %>
      </span>
      <% end %>
     </div>
     </div>
    </div>
  </nav>
 </header>
    <%= yield %>
  </body>
</html>